### ISSUE TITLE
please add option to specify in which folder repo is clonning

### ISSUE THREAD

**Issue by TheRestlessSloth** [Bandeapart1964/PuppyGitPro#2]
Your app is great, but it can't be used on non-root'able devices
I wanted to use it for syncing obsidian vault with git, but the android explorer can't get into ``` Android/data/com.catpuppyapp.puppygit.play.pro/files/PuppyGitRepos/my-obsidian-vault ```  

Can you add function to specify folder in which repo will be cloned?

**Comment by Bandeapart1964** [comment]
I'll do some test, if everything fine, I'll support this feature

**Comment by Bandeapart1964** [comment]
hi, I do some simple tests, is able clone repos to external storage(eg /sdcard/something), but I need consider how make it in puppygit with a properly way, so, plz expect, it will implement in further version

**Comment by Bandeapart1964** [comment]
@TheRestlessSloth , try new version, now support clone repo to external storage:

https://github.com/Bandeapart1964/PuppyGitPro/releases/

**Comment by TheRestlessSloth** [comment]
superb! it workes!

**Comment by Bandeapart1964** [comment]
> superb! it works!

obsidian+pippygit is really great way for manage notes on Android 👍
