### ISSUE TITLE
plz make commit more accessable and intuitive

### ISSUE THREAD

**Issue by TheRestlessSloth** [Bandeapart1964/PuppyGitPro#3]
I have 3 suggestions about commit and push procedure
- if "push" button is pressed without any commit, it need to create commit with all the changed files (like in vscode), ofcourse it need to ask for commit message
- " ChangeList -> Index not clean" is not intuitive at all, can you please make one page for listing all staged/unstaged files (can be differenciated with green/red color)
- if there is no commits to push - push button will be grey or smth like that

**Comment by Bandeapart1964** [comment]
I'll consider

**Comment by Bandeapart1964** [comment]
> I have 3 suggestions about commit and push procedure
> - if "push" button is pressed without any commit, it need to create commit with all the changed files (like in vscode), ofcourse it need to ask for commit message
> - " ChangeList -> Index not clean" is not intuitive at all, can you please make one page for listing all staged/unstaged files (can be differenciated with green/red color)
> - if there is no commits to push - push button will be grey or smth like that


1 I feel is not necessary
2 most time I do not check index page, you can try long press or tap item icon for enable select mode, it will show a bottom bar, then you can easy commit items and sync with upstream 
3 is not necessary too, if no commit need push, I even don't check the push button, so is enabled or disabled, whatever

**Comment by Bandeapart1964** [comment]
> > I have 3 suggestions about commit and push procedure
> > - if "push" button is pressed without any commit, it need to create commit with all the changed files (like in vscode), ofcourse it need to ask for commit message
> > - " ChangeList -> Index not clean" is not intuitive at all, can you please make one page for listing all staged/unstaged files (can be differenciated with green/red color)
> > - if there is no commits to push - push button will be grey or smth like that
> 
> 
> 1. I feel is not necessary, because commit then push or sync, is very easy in puppygit, need not write more codes to make push and commit mixed
> 2. is not necessary too. most time I check difference and commit and sync my files at ChangeList, I only check index when sometimes is really need. you can try long press or tap item icon for enable select mode at ChangeList, it will show a bottom bar, then you can easy commit items and sync with upstream.
> 3 is not necessary too, if no commit need push, I even don't check the push button, so is enabled or disabled, whatever

**Comment by Bandeapart1964** [comment]
> I have 3 suggestions about commit and push procedure
> - if "push" button is pressed without any commit, it need to create commit with all the changed files (like in vscode), ofcourse it need to ask for commit message
> - " ChangeList -> Index not clean" is not intuitive at all, can you please make one page for listing all staged/unstaged files (can be differenciated with green/red color)
> - if there is no commits to push - push button will be grey or smth like that
> 
> 
1. I feel is not necessary, because commit then push or sync, is very easy in puppygit, need not write more codes to make push and commit mixed
2. is not necessary too. most time I check difference and commit and sync my files at ChangeList, I only check index when sometimes is really need. you can try long press or tap item icon for enable select mode at ChangeList, it will show a bottom bar, then you can easy commit items and sync with upstream.
3 is not necessary too, if no commit need push, I even don't check the push button, so is enabled or disabled, whatever
